f# -*- mode:org -*-
#+startup:fold
  *bpip1b0* : positive pion beam, produce stopped pion output file, default configuration 
  with 0.7T magnetic field
  pi+ lifetime is ON, use for validating the weighted simulation
# ----------------------------------------------------------------------------------------------------
 - directory       : file:./
 - configuration   : [[file:./init_project.py][init_project.py]]
 - submitted jobs  : file:../AAA_SUBMITTED_JOBS
 - grid input      : file:/pnfs/mu2e/resilient/users/murat/
 - grid output     : file:/pnfs/mu2e/scratch/users/murat/workflow
 - output_location : file:/mu2e/data2/users/murat/
 - catalogs        : file:./catalog
 - fcl             : file:../../tmp/pipenu/fcl
# ----------------------------------------------------------------------------------------------------
|------------------+------------------+-----------------+-----------+----------+---------------------------------------------------------------------------------------------|
| stage            | step             | status          | N(events) | N(files) | org file                                                                                    |
|------------------+------------------+-----------------+-----------+----------+---------------------------------------------------------------------------------------------|
| [[file:catalog/s1/su2020.736_6013.s1.org][s1_sim]]           | input_dataset    | bmum0b0s00r0000 | 100000000 |          | none                                                                                        |
|                  | fcl_tarball      | completed       | 100000000 |      249 | file:../tmp_fcl/su2020.bmum.gen_50_200000.s1_sim.fcl.tbz                                    |
| [2020-06-20 Sat] | grid_job         |                 |           |          | file:/pnfs/mu2e/scratch/users/murat/workflow/su2020.bmum.s0_gen.s1_sim/outstage/xxxxxxxx/00 |
|                  | job_output_check | completed       |  10000000 |      249 | file:catalog/s1/su2020.bmum.gen_s0.s1_sim.check_grid_output.log                             |
| [[file:/mu2e/data/users/murat/datasets/su2020/bmum/s1][output_location]]  | output_dataset   | bmum0b0s11r0000 |    435303 |      249 | file:catalog/s1/su2020.bmum.s1_sim.art.files                                                |
|------------------+------------------+-----------------+-----------+----------+---------------------------------------------------------------------------------------------|
| [[file:catalog/s2/su2020.bmum.s2.org][s2_sim]]           | input_dataset    | bmum0b0s11r0000 |           |      249 | file:catalog/s1/su2020.bmum.s1_sim.art.files                                                |
|                  | fcl_tarball      | completed       |           |       20 | file:../tmp_fcl/su2020.bmum.s1_sim.s2_sim.fcl.tbz                                           |
| [2020-06-07 Sun] | grid_job         |                 |           |          |                                                                                             |
|                  | job_output_check | completed       |           |       20 | file:catalog/s2/su2020.bmum.s1_sim.s2_sim.check_grid_output.log                             |
| [[file:/mu2e/data/users/murat/datasets/su2020/bmum/s2][output_location]]  | output_dataset   | bmum0b0s21r0000 |    435303 |       20 | file:catalog/s2/su2020.bmum.s2_sim.art.files                                                |
|                  |                  | bmum0b0s22r0000 |           |          |                                                                                             |
|------------------+------------------+-----------------+-----------+----------+---------------------------------------------------------------------------------------------|
| [[file:catalog/s3/su2020.bmum.s3.org][s3_sim]]           | input_dataset    | bmum0b0s21r000  |    435303 |       20 | file:catalog/s2/su2020.bmum.s2_sim.art.files                                                |
|                  | fcl_tarball      | completed       |           |       10 | file:../tmp_fcl/su2020.bmum.s2_sim.s3_sim.fcl.tbz                                           |
|                  | grid_job         |                 |           |          |                                                                                             |
|                  | job_output_check | completed       |           |       10 | file:catalog/s3/su2020.bmum0.s2_s1.s3_sim.check_grid_output.log                             |
|                  | output_dataset   | bmum0b0s31r0000 |    159886 |       10 | file:catalog/s3/su2020.bmum0.s3_ootstops.art.files                                          |
| [[file:/mu2e/data/users/murat/datasets/su2020/bmum/s3][output_location]]  | output_dataset   | bmum0b0s32r0000 |           |       10 | file:catalog/s3/su2020.bmum0.s3_tgtstops.art.files                                          |
|------------------+------------------+-----------------+-----------+----------+---------------------------------------------------------------------------------------------|
| [[file:catalog/s3/su2020.bmum.s3.org][s3_stn_tgtstops]]  | input_dataset    | bmum0s31b0.art  |    159886 |       10 | file:catalog/s3/su2020.bmum.s3_tgtstops.art.files                                           |
|                  | fcl_tarball      | completed       |           |        1 | file:../tmp_fcl/su2020.bmum.s3_tgtstops.s3_stn.fcl.tbz                                      |
|                  | grid_job         | intractv        |           |          |                                                                                             |
| [[file:/mu2e/data/users/murat/datasets/su2020/bmum/s3_stn_tgtstops][output_location]]  | output_dataset   | bmum0s31b0.stn  |           |        1 | file:catalog/s3/su2020.bmum.s3_tgtstops.stn.files                                           |
|                  | stntuple_catalog | completed       |           |        1 | file:/publicweb/m/murat/cafdfc/su2020/bmum.s3_tgtstops                                      |
|------------------+------------------+-----------------+-----------+----------+---------------------------------------------------------------------------------------------|



|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| job                           | input dsid                      |  Nevents | Resampling | Nfiles | Nfiles | Njobs | output_dsid                     | Nfiles |  Nevents |    Nev | upload  | comments                          |
|                               |                                 |          |     factor |        |  / job |       |                                 |        |          |  /file |         |                                   |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| [[file:s1_muon_beam_bmum0.fcl][s1_sim_e9]]                     | bmum0s00b0                      |      1e9 |          1 |        |      1 |  4000 | bmum0s11b0                      |   3996 | 29502600 |   7400 |         | S1, everything relevant           |
| [[file:s1_concat_bmum0.fcl][s1_concat]]                     | bmum0s11b0                      | 29502600 |          1 |   3996 |     20 |   200 | sim.murat.bmum0s11b0.su2020.art |    200 | 29502600 | 147500 | on tape |                                   |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s1_spmc_ele_filter            | sim.murat.bmum0s11b0.su2020.art | 29502600 |          1 |    200 |     20 |    10 | sim.murat.bmum0s16b0.su2020.art |     10 |   247071 |  24700 |         | S1, events with P>100 MeV/c e-    |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s2_sim                        | sim.murat.bmum0s11b0.su2020.art | 29502600 |          1 |    200 |      1 |   200 | sim.murat.bmum0s21b0.su2020.art |    200 |  5352646 |  27000 |         | S2, everything                    |
| s2_concat                     | sim.murat.bmum0s21b0.su2020.art |  5352646 |          1 |    200 |      5 |    40 | sim.murat.bmum0s21b0.su2020.art |     40 |  5352646 | 135000 | on tape |                                   |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s2_sim_ele                    | sim.murat.bmum0s16b0.su2020.art |   247071 |          1 |     10 |     10 |     1 | sim.murat.bmum0s26b0.su2020.art |      1 |      572 |    572 |         | S2, events with S1 P>100 MeV/c e- |
| s2_sim_muo                    | sim.murat.bmum0s11b0.su2020.art | 29502600 |          1 |    200 |     20 |    10 | sim.murat.bmum0s27b0.su2020.art |     20 |  5349397 | 270000 |         | S2,                               |
| s2_spmc_ele_filter            | sim.murat.bmum0s27b0.su2020.art |  5349360 |          1 |     20 |     20 |     1 | sim.murat.bmum0s28b0.su2020.art |      1 |       48 |     48 |         | mu- --> e- decays at Stage2       |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s3_sim                        | sim.murat.bmum0s21b0.su2020.art |  5352646 |          1 |    200 |      1 |   200 | sim.murat.bmum0s31b0.su2020.art |        |          |        | on tape | mu, pi stopped in the ST          |
|                               |                                 |          |            |        |        |       | sim.murat.bmum0s32b0.su2020.art |        |          |        | on tape | mu, pi stopped outside the ST     |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s3_sim_ele                    | sim.murat.bmum0s26b0.su2020.art |      571 |          1 |      1 |      1 |     1 | sim.murat.bmum0s36b0.su2020.art |      1 |       21 |     21 |         | S1 100 MeV/c e- traced to VD9     |
| s3_sim_muo                    | sim.murat.bmum0s27b0.su2020.art |  5349360 |          1 |     20 |      1 |    20 | sim.murat.bmum0s37b0.su2020.art |     20 |  4394759 | 220000 |         | mu- traced to VD9                 |
| s3_sim_ele_28                 | sim.murat.bmum0s28b0.su2020.art |       48 |          1 |      1 |      1 |     1 | sim.murat.bmum0s38b0.su2020.art |      1 |        9 |      9 |         | S2  100 MeV/c e- traced to VD9    |
| s3_spmc_ele_filter            | sim.murat.bmum0s37b0.su2020.art |  4394759 |          1 |     20 |     20 |     1 | sim.murat.bmum0s39b0.su2020.art |      1 |       11 |     11 |         | mu- --> e- decays at Stage3       |
| [[file:s3_spmc_muo_filter_bmum0.fcl][s3_spmc_muo_filter]]            | sim.murat.bmum0s37b0.su2020.art |  4394759 |          1 |     20 |     20 |     1 | sim.murat.bmum0s3ab0.su2020.art |      1 |     4065 |   4065 |         | P>100 MeV/c mu- at VD9            |
| s3_sim_vd9                    | sim.murat.bmum0s21b0.su2020.art |  5352646 |            |        |        |       | sim.murat.bmum0s3cb0.su2020.art |        |          |        |         | everything traced to VD9,         |
| s3_add_proton_time_map_s3c    | sim.murat.bmum0s3cb0.su2020.art |          |            |        |        |       | sim.murat.bmum0s3cb0.su2020.art |        |          |        |         |                                   |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s4_sim_muo_vd10               | sim.murat.bmum0s37b0.su2020.art |  4394759 |          1 |     20 |      1 |    20 | sim.murat.bmum0s47b0.su2020.art |     20 |  3332703 | 170000 |         | mu- traced to VD10                |
| s4_spmc_muo_filter            | sim.murat.bmum0s47b0.su2020.art |  3332583 |          1 |     20 |     20 |     1 | sim.murat.bmum0s4bb0.su2020.art |      1 |   263950 |        |         | mu- P>70 MeV/c at VD10            |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s5_resample_vd9_to_mother_s36 | sim.murat.bmum0s36b0.su2020.art |       21 |      10000 |    100 |      1 |   100 | sim.murat.bmum0s56b0.su2020.art |      1 |   410134 | 410134 |         | S1 e- scattering in the ST (p>0)  |
| s5_resample_vd9_to_mother_s3a | sim.murat.bmum0s3ab0.su2020.art |  4394759 |            |     20 |        |       | sim.murat.bmum0s57b0.su2020.art |        |          |        |         | mu- scattering in the ST          |
| s5_resample_vd9_to_mother_s38 | sim.murat.bmum0s38b0.su2020.art |        9 |      10000 |    100 |      1 |   100 | sim.murat.bmum0s58b0.su2020.art |      1 |          |        |         | S2 e- scattering in the ST        |
| s5_resample_vd9_to_mother_s39 | sim.murat.bmum0s39b0.su2020.art |       11 |      10000 |    100 |      1 |   100 | sim.murat.bmum0s59b0.su2020.art |      1 |          |        |         | S3 e- scattering in the ST        |
| s5_resample_vd10_to_mother    | sim.murat.bmum0s4bb0.su2020.art |   263950 |       1000 |    264 |      1 |   264 | sim.murat.bmum0s5bb0.su2020.art |        |          |        |         | mu- decays in flight              |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|
| s5_stn_s56                    | sim.murat.bmum0s56b0.su2020.art |   410134 |          1 |      1 |      1 |     1 | nts.murat.bmum0s56b0.su2020.stn |      1 |   410134 | 410134 |         | S1 e- scattering in the ST  (p>0) |
| s5_stn_s58                    | sim.murat.bmum0s58b0.su2020.art |          |          1 |      1 |      1 |     1 | nts.murat.bmum0s58b0.su2020.stn |      1 |          |        |         | S1 e- scattering in the ST  (p>0) |
| s5_stn_s59                    | sim.murat.bmum0s59b0.su2020.art |          |          1 |      1 |      1 |     1 | nts.murat.bmum0s59b0.su2020.stn |      1 |          |        |         | S1 e- scattering in the ST  (p>0) |
| s5_stn_s5a                    | sim.murat.bmum0s5ab0.su2020.art |          |          1 |      1 |      1 |     1 | nts.murat.bmum0s5ab0.su2020.stn |      1 |          |        |         | mu- scattering in the ST          |
| s5_stn_s5b                    | sim.murat.bmum0s5bb0.su2020.art |          |          1 |      1 |      1 |     1 | nts.murat.bmum0s5bb0.su2020.stn |      1 |          |        |         | mu- decays in flight              |
|-------------------------------+---------------------------------+----------+------------+--------+--------+-------+---------------------------------+--------+----------+--------+---------+-----------------------------------|

* ---------------------------------------------------------------------------------------------------------------
* data formats                                                                                                
* ---------------------------------------------------------------------------------------------------------------
* sim.mu2e.pbar2m.bmum0b0s11r0000.art                                                                         
** 16-Oct-2023                                                                                                
murat@mu2ebuild01:/mu2e/app/users/murat/muse>mu2e -c Offline/Print/fcl/dumpDataProducts.fcl results/2023-10-16-20-26.s1_sim_bmum0b0.mu2ebuild01.12844/sim.mu2e.bmum0b0s11r0000.pbar2m.001210_00000000.art
   ************************** Mu2e Offline **************************
     art v3_13_02    root v6_28_04c    KinKal v02_04_02
     build  /mu2e/app/users/murat/muse
     build  sl7-prof-e20-p047    10/16/23 20:25:33
   ******************************************************************
16-Oct-2023 21:15:45 CDT  Initiating request to open input file "results/2023-10-16-20-26.s1_sim_bmum0b0.mu2ebuild01.12844/sim.mu2e.bmum0b0s11r0000.pbar2m.001210_00000000.art"
16-Oct-2023 21:15:45 CDT  Opened input file "results/2023-10-16-20-26.s1_sim_bmum0b0.mu2ebuild01.12844/sim.mu2e.bmum0b0s11r0000.pbar2m.001210_00000000.art"
Begin processing the 1st record. run: 1210 subRun: 0 event: 214 at 16-Oct-2023 21:15:47 CDT
Found 5 data products in this Event
Data products: 
Friendly Class Name  Module Label    Instance Name  Process Name     Product ID
mu2e::SimParticlemv    BeamFilter                            POT   198111821
 mu2e::GenParticles      generate                            POT   590160162
 mu2e::StepPointMCs    BeamFilter             Beam           POT  1754366283
 mu2e::StepPointMCs    BeamFilter  virtualdetector           POT  3373559849
     mu2e::StatusG4         g4run                            POT  4179471200

Found 2 data products in this SubRun
Data products: 
        Friendly Class Name    Module Label  Instance Name  Process Name     Product ID
        mu2e::GenEventCount      genCounter                          POT  3358959612
mu2e::PhysicalVolumeInfomvs  compressPVBeam                          POT  3480116073

Found 0 data products in this Run
16-Oct-2023 21:15:47 CDT  Closed input file "results/2023-10-16-20-26.s1_sim_bmum0b0.mu2ebuild01.12844/sim.mu2e.bmum0b0s11r0000.pbar2m.001210_00000000.art"
Art has completed and will exit with status 0.
** 17-Aug-2022                                                                                                
murat@mu2ebuild01:/mu2e/app/users/murat/muse>mu2e -c Offline/Print/fcl/dumpDataProducts.fcl -s /mu2e/app/users/nigrelli/r001/results/bmum0_s1_sim/sim.mu2e.pbar2m.bmum0s11b0.001000_00000000.art 
   ************************** Mu2e Offline **************************
     art v3_11_01    root v6_26_00    KinKal v02_01_00
     build  /mu2e/app/users/murat/muse
     build  sl7-debug-e20-p026    08/16/22 18:16:09
   ******************************************************************
17-Aug-2022 17:36:21 CDT  Initiating request to open input file "/mu2e/app/users/nigrelli/r001/results/bmum0_s1_sim/sim.mu2e.pbar2m.bmum0s11b0.001000_00000000.art"
17-Aug-2022 17:36:21 CDT  Opened input file "/mu2e/app/users/nigrelli/r001/results/bmum0_s1_sim/sim.mu2e.pbar2m.bmum0s11b0.001000_00000000.art"
Begin processing the 1st record. run: 1 subRun: 0 event: 2 at 17-Aug-2022 17:36:23 CDT
Found 5 data products in this Event
Data products: 
Friendly Class Name  Module Label    Instance Name  Process Name     Product ID
     mu2e::StatusG4         g4run                          S1Sim  1104244220
 mu2e::StepPointMCs    BeamFilter           mubeam         S1Sim  1188941664
 mu2e::StepPointMCs    BeamFilter  virtualdetector         S1Sim  1902879461
mu2e::SimParticlemv    BeamFilter                          S1Sim  1934371984
 mu2e::GenParticles      generate                          S1Sim  2398351477

Found 2 data products in this SubRun
Data products: 
        Friendly Class Name    Module Label  Instance Name  Process Name     Product ID
mu2e::PhysicalVolumeInfomvs  compressPVBeam                        S1Sim   766382810
        mu2e::GenEventCount      genCounter                        S1Sim  2509493737

Found 0 data products in this Run
17-Aug-2022 17:36:23 CDT  Closed input file "/mu2e/app/users/nigrelli/r001/results/bmum0_s1_sim/sim.mu2e.pbar2m.bmum0s11b0.001000_00000000.art"
Art has completed and will exit with status 0.

* sim.mu2e.pbar2m.bmum0b0s21r0000.art                                                                         
** 16-Aug-2022                                                                                                
murat@mu2ebuild01:/mu2e/app/users/murat/muse>mu2e -c Offline/Print/fcl/dumpDataProducts.fcl -s results/pbar2m.bmum0.s2_sim/sim.owner.pbar2m.bmum0s21b0.001000_00000000.art 
   ************************** Mu2e Offline **************************
     art v3_11_01    root v6_26_00    KinKal v02_01_00
     build  /mu2e/app/users/murat/muse
     build  sl7-debug-e20-p026    08/14/22 10:44:43
   ******************************************************************
16-Aug-2022 17:10:55 CDT  Initiating request to open input file "results/pbar2m.bmum0.s2_sim/sim.owner.pbar2m.bmum0s21b0.001000_00000000.art"
16-Aug-2022 17:10:55 CDT  Opened input file "results/pbar2m.bmum0.s2_sim/sim.owner.pbar2m.bmum0s21b0.001000_00000000.art"
Begin processing the 1st record. run: 1 subRun: 0 event: 663 at 16-Aug-2022 17:10:58 CDT
Found 6 data products in this Event
Data products: 
Friendly Class Name  Module Label    Instance Name  Process Name     Product ID
     mu2e::StatusG4         g4run                          S2Sim   108074796
mu2e::SimParticlemv    BeamFilter                          S2Sim   887903808
 mu2e::StepPointMCs    BeamFilter         DSVacuum         S2Sim   910930626
 mu2e::StepPointMCs    BeamFilter  virtualdetector         S2Sim   919328821
     mu2e::StatusG4         g4run                          S1Sim  1104244220
 mu2e::GenParticles      generate                          S1Sim  2398351477

Found 3 data products in this SubRun
Data products: 
        Friendly Class Name    Module Label  Instance Name  Process Name     Product ID
mu2e::PhysicalVolumeInfomvs  compressPVBeam                        S1Sim   766382810
mu2e::PhysicalVolumeInfomvs  compressPVBeam                        S2Sim  1779329034
        mu2e::GenEventCount      genCounter                        S1Sim  2509493737

Found 0 data products in this Run
16-Aug-2022 17:10:58 CDT  Closed input file "results/pbar2m.bmum0.s2_sim/sim.owner.pbar2m.bmum0s21b0.001000_00000000.art"
Art has completed and will exit with status 0.
1* ---------------------------------------------------------------------------------------------------------------
* sim.mu2e.pbar2m.bmum0b0s31r0000.art    <2023-10-17 Tue>                                                     
murat@mu2ebuild01:/mu2e/app/users/murat/muse>mu2e -c Offline/Print/fcl/dumpDataProducts.fcl -s sim.mu2e.bmum0b0s31r0000.pbar2m.001210_00000000.art
   ************************** Mu2e Offline **************************
     art v3_13_02    root v6_28_04c    KinKal v02_04_02
     build  /mu2e/app/users/murat/muse
     build  sl7-prof-e20-p047    10/16/23 20:25:33
   ******************************************************************
17-Oct-2023 06:48:50 CDT  Initiating request to open input file "sim.mu2e.bmum0b0s31r0000.pbar2m.001210_00000000.art"
17-Oct-2023 06:48:51 CDT  Opened input file "sim.mu2e.bmum0b0s31r0000.pbar2m.001210_00000000.art"
Begin processing the 1st record. run: 1210 subRun: 0 event: 1086 at 17-Oct-2023 06:48:52 CDT
Found 5 data products in this Event
Data products: 
Friendly Class Name      Module Label    Instance Name  Process Name     Product ID
 mu2e::GenParticles          generate                            POT   590160162
     mu2e::StatusG4             g4run                          S3Sim   990985884
mu2e::SimParticlemv  TargetStopFilter                          S3Sim  1865770519
 mu2e::StepPointMCs  TargetStopFilter  virtualdetector         S3Sim  4027075826
     mu2e::StatusG4             g4run                            POT  4179471200

Found 2 data products in this SubRun
Data products: 
        Friendly Class Name           Module Label  Instance Name  Process Name     Product ID
mu2e::PhysicalVolumeInfomvs  compressPVTargetStops                        S3Sim   603628714
        mu2e::GenEventCount             genCounter                          POT  3358959612

Found 0 data products in this Run
17-Oct-2023 06:48:52 CDT  Closed input file "sim.mu2e.bmum0b0s31r0000.pbar2m.001210_00000000.art"
Art has completed and will exit with status 0.

* sim.mu2e.bpip2b0s24r0000.pipenu.art    <2023-12-08 Fri>                                                     

[tripathy@mu2egpvm02 /exp/mu2e/app/users/tripathy/Development_pipenu]$ mu2e -c Offline/Print/fcl/dumpDataProducts.fcl -s sim.mu2e.bpip2b0s24r0000.pipenu.001210_00000000.art
   ************************** Mu2e Offline **************************
     art v3_13_02    root v6_28_04c    KinKal v02_04_02
     build  /exp/mu2e/app/users/tripathy/Development_pipenu
     build  sl7-prof-e20-p047    11/30/23 16:27:18
   ******************************************************************
08-Dec-2023 11:19:51 CST  Initiating request to open input file "sim.mu2e.bpip2b0s24r0000.pipenu.001210_00000000.art"
08-Dec-2023 11:19:51 CST  Opened input file "sim.mu2e.bpip2b0s24r0000.pipenu.001210_00000000.art"
Begin processing the 1st record. run: 1210 subRun: 0 event: 590 at 08-Dec-2023 11:19:53 CST
Found 5 data products in this Event
Data products: 
Friendly Class Name        Module Label    Instance Name  Process Name     Product ID
mu2e::SimParticlemv  DegraderStopFilter                          S2Sim    73722960
     mu2e::StatusG4               g4run                          S2Sim   108074796
 mu2e::GenParticles            generate                            POT   590160162
 mu2e::StepPointMCs  DegraderStopFilter  virtualdetector         S2Sim  1466492717
     mu2e::StatusG4               g4run                            POT  4179471200

Found 2 data products in this SubRun
Data products: 
        Friendly Class Name           Module Label  Instance Name  Process Name     Product ID
mu2e::PhysicalVolumeInfomvs  compressPVTargetStops                        S2Sim   513445146
        mu2e::GenEventCount             genCounter                          POT  3358959612

Found 0 data products in this Run
08-Dec-2023 11:19:53 CST  Closed input file "sim.mu2e.bpip2b0s24r0000.pipenu.001210_00000000.art"
Art has completed and will exit with status 0.

* ---------------------------------------------------------------------------------------------------------------
* performance testing (prof build)                                                                            
** stage 1 (up to DS)                                                                                         

|    nevents | mode  | BField           | N(mu) | N(muon stops) | N(oot) |    CPU |    real | comment                   |
|------------+-------+------------------+-------+---------------+--------+--------+---------+---------------------------|
|      10000 | debug |                  |       |               |        | 939.23 | 730.937 |                           |
|      10000 | prof  |                  |       |               |        | 383.67 | 224.188 |                           |
|      20000 | prof  | bfgeom_v01       |    74 |            28 |        | 701.42 | 383.228 |                           |
|      20000 | prof  | bfgeom_no_ds_v01 |    73 |            25 |        | 701.42 | 383.228 |                           |
|     200000 | prof  | bfgeom_no_ds_v01 |   883 |           317 |    539 |        |         |                           |
|     200000 | prof  | bfgeom_v01       |   887 |           332 |    532 |        |         |                           |
|------------+-------+------------------+-------+---------------+--------+--------+---------+---------------------------|
| w/o offset |       |                  |       |               |        | 317.75 |         |                           |
|  per event |       |                  |       |               |        | 3.2e-2 |         | count on 100K events/hour |
|            |       |                  |       |               |        |        |         |                           |
#+TBLFM: @4$7=@3$7-@2$7

MemReport  ---------- Memory summary [base-10 MB] ------
MemReport  VmPeak = 2690.95 VmHWM = 1964.63
*** Aug 2022                                                                                                  
       : (230 sec ~ 4min) / 5000 events on mu2ebuild01: 75,000 events/hour
	  250,000 events     : < 4 hours
          100,000,000 events : 400 segments with the time request of, say, 10 hours

	  MemReport          : VmPeak = 2254.73 VmHWM = 1659.85 < 2 GBytes

	  output             : 154 events out of 5000
* test no DS field option  N(POT)=20000                                                                       
** stopped muons no DS    field : 25 stopped muons                                                            
TrigReport ---------- Module summary ------------
TrigReport    Visited        Run     Passed     Failed      Error Name
TrigReport         73         73         73          0          0 IPAMuonFinder
TrigReport         73         73          0         73          0 IPAStopFilter
TrigReport         73          0          0          0          0 IPAStopOutput
TrigReport         73         73         73          0          0 TargetMuonFinder
TrigReport         73         73         25         48          0 TargetStopFilter
TrigReport         73         25         25          0          0 TargetStopOutput
TrigReport         73         73         73          0          0 TargetStopPrescaleFilter
TrigReport          0          0          0          0          0 compressPVIPAStops
TrigReport         47         47         47          0          0 compressPVOOTStops
TrigReport         25         25         25          0          0 compressPVTargetStops
TrigReport        219         73         73          0          0 g4consistentFilter
TrigReport        219         73         73          0          0 g4run
TrigReport         73         73         73          0          0 ootMuonFinder
TrigReport         73         73         47         26          0 ootStopFilter
TrigReport         73         47         47          0          0 ootStopOutput

** stopped muons standard field : 28 stopped muons                                                            
TrigReport ---------- Module summary ------------
TrigReport    Visited        Run     Passed     Failed      Error Name
TrigReport         74         74         74          0          0 IPAMuonFinder
TrigReport         74         74          0         74          0 IPAStopFilter
TrigReport         74          0          0          0          0 IPAStopOutput
TrigReport         74         74         74          0          0 TargetMuonFinder
TrigReport         74         74         28         46          0 TargetStopFilter
TrigReport         74         28         28          0          0 TargetStopOutput
TrigReport         74         74         74          0          0 TargetStopPrescaleFilter
TrigReport          0          0          0          0          0 compressPVIPAStops
TrigReport         45         45         45          0          0 compressPVOOTStops
TrigReport         28         28         28          0          0 compressPVTargetStops
TrigReport        222         74         74          0          0 g4consistentFilter
TrigReport        222         74         74          0          0 g4run
TrigReport         74         74         74          0          0 ootMuonFinder
TrigReport         74         74         45         29          0 ootStopFilter
TrigReport         74         45         45          0          0 ootStopOutput

* ---------------------------------------------------------------------------------------------------------------
* back to summary: [[file:../../doc/datasets.org][pipenu/doc/datasets.org]]
* ---------------------------------------------------------------------------------------------------------------
