#!/bin/bash
# echo pwd  `pwd`
#------------------------------------------------------------------------------
# make sure Stntuple build_config is executed
#------------------------------------------------------------------------------
base=$MUSE_WORK_DIR

# echo pipenu::build_config_muse:000: MU2E_VERBOSE:.$MU2E_VERBOSE.
# echo pipenu::build_congig_muse:001: pwd=`pwd`

# pushd $MUSE_WORK_DIR ; Stntuple/scripts/build_config_muse pipenu ; popd ;
cd $MUSE_WORK_DIR ; Stntuple/scripts/build_config_muse pipenu ; cd ~- ;
#------------------------------------------------------------------------------
# 'pipenu' and its subpackages, excluding Stntuple
#------------------------------------------------------------------------------
# pkg=`pwd | awk -F / '{print $(NF-1)}'`
pkg=`echo $0 | awk -F / '{print $(NF-2)}'`

# echo "pipenu::build_congig_muse:002: pwd="`pwd`   pkg=$pkg

pkg_include_dir=$base/include/$pkg

if [ ! -d $pkg_include_dir ] ; then
    echo pkg::build_config_muse: pwd=$pwd ; creating $base/include/$pkg
    mkdir -p $pkg_include_dir
fi

for d in ana ; do
    if [ ! -e $pkg_include_dir/$d ] ; then 
	cmd="ln -s ../../$pkg/$d/$d $pkg_include_dir/$d"
	echo `pwd`$0 : executing: $cmd
	$cmd
    fi
done
